export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const REQUEST_POSTS = 'POST/REQUEST_POSTS'
export const FETCH_POSTS = "POST/FETCH_POSTS"


export const ACTION_NEW_EXHIBITIONS = "EXHIBITIONS/ACTION_NEW_EXHIBITIONS"
export const FETCH_NEW_EXHIBITIONS = "EXHIBITIONS/FETCH_NEW_EXHIBITIONS"